// Automatically generated by scan-portfolio utility
export interface MediaItem {
    type: 'video' | 'image';
    url: string;
}

export interface Project {
    id: number;
    title: string;
    category: string;
    type: string;
    desc: string;
    details: string;
    niche?: string;
    externalLink?: string;
    media: MediaItem[];
}

export const projects: Project[] = [
    {
        "id": 1,
        "title": "Apex of Sound",
        "category": "Photo",
        "type": "image",
        "desc": "Translating the roaring energy of a live concert into static frames of visual adrenaline.",
        "details": "This collection is an exercise in capturing chaos with clarity. We dove into the heart of the crowd and the stage, using fast lenses and predictive tracking to isolate moments of pure sonic fury. The edit blends sharp, vivid subject isolation with intentional motion blur and atmospheric lens flares to recreate the feeling of being there. It's about more than just photos of a band; it's about bottling the thunder of the amplifiers and the electricity of the audience.",
        "media": [
            {
                "type": "image",
                "url": "/portfolio/Photo/Concert/01.jpg"
            },
            {
                "type": "image",
                "url": "/portfolio/Photo/Concert/02.jpg"
            }
        ]
    },
    {
        "id": 2,
        "title": "Electric Soul Live",
        "category": "Photo",
        "type": "image",
        "desc": "Capturing the raw, unfiltered energy of live performance through high-contrast cinematic photography.",
        "details": "This session was about freezing the peak moment of artistic expression. We utilized a mix of vintage film grain processing and modern high-dynamic range capture to showcase the 'Electric Soul' of the performer. Every shot is a testament to our professional ability to capture movement, emotion, and the neon-soaked atmosphere of the stage. This is commercial photography at its most visceral.",
        "media": [
            {
                "type": "image",
                "url": "/portfolio/Photo/Electric-Soul-Performance/01.jpg"
            },
            {
                "type": "image",
                "url": "/portfolio/Photo/Electric-Soul-Performance/02.jpg"
            }
        ]
    },
    {
        "id": 3,
        "title": "The Ninethcloud Cut",
        "category": "Video",
        "type": "video",
        "desc": "A raw look into our creative process focused on movement and high-fidelity production.",
        "details": "This project explores the intersection of cinematic visuals and brand storytelling. We focused on capturing the 'Ninethcloud' essence of the creator economy. It involved high-speed cameras and professional grading.",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/The-Unpolished-Cut/01.mp4"
            }
        ]
    },
    {
        "id": 4,
        "title": "Ethereal",
        "category": "Websites",
        "niche": "E commerce",
        "type": "website",
        "desc": "A high-performance E commerce website.",
        "details": "Direct live preview of Ethereal project.",
        "externalLink": "https://ethereal-jewellery.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fethereal-jewellery.vercel.app%2F"
            }
        ]
    },
    {
        "id": 5,
        "title": "Shilpa Interiors",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Shilpa Interiors project.",
        "externalLink": "https://shilpa-interiors.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fshilpa-interiors.vercel.app%2F"
            }
        ]
    },
    {
        "id": 6,
        "title": "Wanderlust",
        "category": "Websites",
        "niche": "Travel Agency",
        "type": "website",
        "desc": "A high-performance Travel Agency website.",
        "details": "Direct live preview of Wanderlust project.",
        "externalLink": "https://wanderlust-india-premium.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fwanderlust-india-premium.vercel.app%2F"
            }
        ]
    }
];
