// Automatically generated by scan-portfolio utility
export interface MediaItem {
    type: 'video' | 'image';
    url: string;
}

export interface Project {
    id: number;
    title: string;
    category: string;
    type: string;
    desc: string;
    details: string;
    niche?: string;
    externalLink?: string;
    media: MediaItem[];
}

export const projects: Project[] = [
    {
        "id": 1,
        "title": "Interior By Dreamspace - Social Media Content",
        "category": "Video",
        "type": "video",
        "desc": "Social media content and ad creatives for interior design brand showcasing modern home transformations",
        "details": "Short-form video content designed for Instagram Reels and paid advertising campaigns. Features before/after transformations, room tours, and design inspiration for residential projects.",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Interior-By-Dreamspace-Social-Media/AQN7-ivNgTGRdpWTfcrE6yNCE3FfdQaJ3RIyGPKzORd2Mnm7RbkFisDKVsj23hb_6uGEZiPRw_7GeD1H63o2GRYm.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/Interior-By-Dreamspace-Social-Media/AQNiLEsA15f7HCOAPXIZSXAOxvSHg07HQ4cjjkZ3IW8WmwSF6gJ_dQWkYaPVYCEc93zeqnc4Pmy2WeNShZ3fYvjC6gxS26gpU2n3jZ0.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/Interior-By-Dreamspace-Social-Media/AQP9-WkfHd7lKu_JczsW_CVi73IuqZDuCPOzyY1VYwSd-5ddWXaFnFGFPvx2ELdvdsK5aLZacuJ5SaaeuZlBsfZT6iG5En6gZohR69Q.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/Interior-By-Dreamspace-Social-Media/AQPCdMM9edhmJzd2AfUd_jbgEhpmwlq3T22kLRfouTikPSDyeX662_8IK4K4IFR6PaGgtpwd0eULvim0TIuNoG5Ty5wf165qIYK6rgg.mp4"
            }
        ]
    },
    {
        "id": 2,
        "title": "Kav Kriti - Social Media Content",
        "category": "Video",
        "type": "video",
        "desc": "Social media content and ad creatives for interior design brand showcasing luxury spaces and design details",
        "details": "Short-form video content designed for Instagram Reels and paid advertising campaigns. Features detailed design elements, material showcases, and luxury interior highlights.",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Kav-Kriti-Social-Media/AQMJRlbysTDxv-iiAvOXleg-jOkRL-IDCe1x04JfZE1pogmiPOYObbIS-mQBrDvs6NMdas_7hvNbGqDYPPHfWWi5Io48Rsb3za0iIHM.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/Kav-Kriti-Social-Media/AQOhX9a-Xwy8pFEjkamq9E_80wNqp59k_T2TYkhIJB7flQJ554x0LqK7gPKZlk40fpXUnDUU7NudyKYZpSnF4NlBjKETV0KMYkIon7M.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/Kav-Kriti-Social-Media/AQPHpYVdLDNzMBZRm7dWW-fXmljGYBgZy50at9kvGNKPD1L5JI8Zxdre9V1f8JJD8x_fBuEingpwYqz6nOjAkL7Pbzut1tYOIwFVNTc.mp4"
            }
        ]
    },
    {
        "id": 3,
        "title": "SBBI Interiors - Social Media Content",
        "category": "Video",
        "type": "video",
        "desc": "Social media content and ad creatives for interior design brand showcasing transformations and project highlights",
        "details": "Short-form video content designed for Instagram Reels and paid advertising campaigns to attract high-ticket interior design clients. Features room transformations, design tips, and project showcases.",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/SBBI-Interiors-Social-Media/AQNT8uel7U2XHZowCuKSUYeBUR1g67ipDETtMqYuFJuSOrYvPDyzQIL61anPw5vb_hXGS8ZKuN-hymeq99kasfJO-PLvwj77Jn_Va-I.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/SBBI-Interiors-Social-Media/AQPQIHcCmF3LwGbXHsoxEstvP7wxEb00N-d1pm-p0dnAJt7jxng-uhCqodtdah-sEcpBo0GFr49RZEZH6ec9iczzx5ZDB4uaKVeJ6FY (1).mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/SBBI-Interiors-Social-Media/AQPQIHcCmF3LwGbXHsoxEstvP7wxEb00N-d1pm-p0dnAJt7jxng-uhCqodtdah-sEcpBo0GFr49RZEZH6ec9iczzx5ZDB4uaKVeJ6FY.mp4"
            },
            {
                "type": "video",
                "url": "/portfolio/Video/SBBI-Interiors-Social-Media/AQPpVaq0QXILf_15hq8pvYJB-En76vSBfixpjR1p3XK3HSc4SvRO3nDduiB_6yVoiRMNThDKOalvIjZFZtEqtstM8cYNNybni0yW0F0.mp4"
            }
        ]
    },
    {
        "id": 4,
        "title": "Video Showcase 1",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-1/AQNA66VLWTpJk6NljGw5Lc1Hi7iWEVY5j9kkC6GEUcexkjLlrCtpkEnDnzc69GU1FDIMo-CNs4H5SeMCz9YRkm9Tmjxnc4wXBsVasQ0.mp4"
            }
        ]
    },
    {
        "id": 5,
        "title": "Video Showcase 2",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-2/AQNZLeNjba0Fhu8zOaTcoy77cWShDs02CT89TR1QPuY6_3PKUVWKHlY2z3OqgVzeC7yk5dEbnaHRcg6LRMQKbLu6oNDb1IO0ufULeoU.mp4"
            }
        ]
    },
    {
        "id": 6,
        "title": "Video Showcase 3",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-3/AQO5BDlnO7r1Hoew0PQR_jEr0E1FZMCiW6-HRP4smpvLl4VHGt-d4PAc11RIk6ykxUnF_JCjFL5enoq-A5VJrMWC-D2jnn7KaSt82Cw.mp4"
            }
        ]
    },
    {
        "id": 7,
        "title": "Video Showcase 4",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-4/AQOb1V_Gx-uj74949AgpeGKcJMAVxWzh0ZPWE8fD_Dfwdr5XKu0hDQwdW2xjbj9dN3KxxSEuQU8kBgkgROa2c3_O.mp4"
            }
        ]
    },
    {
        "id": 8,
        "title": "Video Showcase 5",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-5/AQOip5EdKR0Lx6ycZ9NeGUFWRUv9c1RnIjpZ1qqdBlOBHRkjeVdL4O5-LdTNg8Qohu0x-nb5LtX1ajUye3NwX3uWwCtjwneJ49gjNRM.mp4"
            }
        ]
    },
    {
        "id": 9,
        "title": "Ethereal",
        "category": "Websites",
        "niche": "E commerce",
        "type": "website",
        "desc": "A high-performance E commerce website.",
        "details": "Direct live preview of Ethereal project.",
        "externalLink": "https://ethereal-jewellery.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fethereal-jewellery.vercel.app%2F"
            }
        ]
    },
    {
        "id": 10,
        "title": "Forge Fitness",
        "category": "Websites",
        "niche": "Fitness",
        "type": "website",
        "desc": "A high-performance Fitness website.",
        "details": "Direct live preview of Forge Fitness project.",
        "externalLink": "https://forge-fitness-smoky.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fforge-fitness-smoky.vercel.app%2F"
            }
        ]
    },
    {
        "id": 11,
        "title": "Atelier Stone",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Atelier Stone project.",
        "externalLink": "https://atelier-stone.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fatelier-stone.vercel.app%2F"
            }
        ]
    },
    {
        "id": 12,
        "title": "Roop Stone Impex",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Roop Stone Impex project.",
        "externalLink": "https://roop-stone-impex.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Froop-stone-impex.vercel.app%2F"
            }
        ]
    },
    {
        "id": 13,
        "title": "Shilpa Interiors",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Shilpa Interiors project.",
        "externalLink": "https://shilpa-interiors.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fshilpa-interiors.vercel.app%2F"
            }
        ]
    },
    {
        "id": 14,
        "title": "SRK Interior",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of SRK Interior project.",
        "externalLink": "https://srk-interior.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fsrk-interior.vercel.app%2F"
            }
        ]
    },
    {
        "id": 15,
        "title": "Vanya&Vastu",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Vanya&Vastu project.",
        "externalLink": "https://vanya-vastu.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fvanya-vastu.vercel.app%2F"
            }
        ]
    },
    {
        "id": 16,
        "title": "Wanderlust",
        "category": "Websites",
        "niche": "Travel Agency",
        "type": "website",
        "desc": "A high-performance Travel Agency website.",
        "details": "Direct live preview of Wanderlust project.",
        "externalLink": "https://wanderlust-india-premium.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fwanderlust-india-premium.vercel.app%2F"
            }
        ]
    }
];
