// Automatically generated by scan-portfolio utility
export interface MediaItem {
    type: 'video' | 'image';
    url: string;
}

export interface Project {
    id: number;
    title: string;
    category: string;
    type: string;
    desc: string;
    details: string;
    niche?: string;
    externalLink?: string;
    media: MediaItem[];
}

export const projects: Project[] = [
    {
        "id": 1,
        "title": "Video Showcase 1",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-1/AQNA66VLWTpJk6NljGw5Lc1Hi7iWEVY5j9kkC6GEUcexkjLlrCtpkEnDnzc69GU1FDIMo-CNs4H5SeMCz9YRkm9Tmjxnc4wXBsVasQ0.mp4"
            }
        ]
    },
    {
        "id": 2,
        "title": "Video Showcase 2",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-2/AQNZLeNjba0Fhu8zOaTcoy77cWShDs02CT89TR1QPuY6_3PKUVWKHlY2z3OqgVzeC7yk5dEbnaHRcg6LRMQKbLu6oNDb1IO0ufULeoU.mp4"
            }
        ]
    },
    {
        "id": 3,
        "title": "Video Showcase 3",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-3/AQO5BDlnO7r1Hoew0PQR_jEr0E1FZMCiW6-HRP4smpvLl4VHGt-d4PAc11RIk6ykxUnF_JCjFL5enoq-A5VJrMWC-D2jnn7KaSt82Cw.mp4"
            }
        ]
    },
    {
        "id": 4,
        "title": "Video Showcase 4",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-4/AQOb1V_Gx-uj74949AgpeGKcJMAVxWzh0ZPWE8fD_Dfwdr5XKu0hDQwdW2xjbj9dN3KxxSEuQU8kBgkgROa2c3_O.mp4"
            }
        ]
    },
    {
        "id": 5,
        "title": "Video Showcase 5",
        "category": "Video",
        "type": "video",
        "desc": "Original Video project.",
        "details": "",
        "media": [
            {
                "type": "video",
                "url": "/portfolio/Video/Video-Showcase-5/AQOip5EdKR0Lx6ycZ9NeGUFWRUv9c1RnIjpZ1qqdBlOBHRkjeVdL4O5-LdTNg8Qohu0x-nb5LtX1ajUye3NwX3uWwCtjwneJ49gjNRM.mp4"
            }
        ]
    },
    {
        "id": 6,
        "title": "Ethereal",
        "category": "Websites",
        "niche": "E commerce",
        "type": "website",
        "desc": "A high-performance E commerce website.",
        "details": "Direct live preview of Ethereal project.",
        "externalLink": "https://ethereal-jewellery.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fethereal-jewellery.vercel.app%2F"
            }
        ]
    },
    {
        "id": 7,
        "title": "Forge Fitness",
        "category": "Websites",
        "niche": "Fitness",
        "type": "website",
        "desc": "A high-performance Fitness website.",
        "details": "Direct live preview of Forge Fitness project.",
        "externalLink": "https://forge-fitness-smoky.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fforge-fitness-smoky.vercel.app%2F"
            }
        ]
    },
    {
        "id": 8,
        "title": "Atelier Stone",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Atelier Stone project.",
        "externalLink": "https://atelier-stone.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fatelier-stone.vercel.app%2F"
            }
        ]
    },
    {
        "id": 9,
        "title": "Roop Stone Impex",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Roop Stone Impex project.",
        "externalLink": "https://roop-stone-impex.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Froop-stone-impex.vercel.app%2F"
            }
        ]
    },
    {
        "id": 10,
        "title": "Shilpa Interiors",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Shilpa Interiors project.",
        "externalLink": "https://shilpa-interiors.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fshilpa-interiors.vercel.app%2F"
            }
        ]
    },
    {
        "id": 11,
        "title": "SRK Interior",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of SRK Interior project.",
        "externalLink": "https://srk-interior.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fsrk-interior.vercel.app%2F"
            }
        ]
    },
    {
        "id": 12,
        "title": "Vanya&Vastu",
        "category": "Websites",
        "niche": "Interior Design",
        "type": "website",
        "desc": "A high-performance Interior Design website.",
        "details": "Direct live preview of Vanya&Vastu project.",
        "externalLink": "https://vanya-vastu.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fvanya-vastu.vercel.app%2F"
            }
        ]
    },
    {
        "id": 13,
        "title": "Wanderlust",
        "category": "Websites",
        "niche": "Travel Agency",
        "type": "website",
        "desc": "A high-performance Travel Agency website.",
        "details": "Direct live preview of Wanderlust project.",
        "externalLink": "https://wanderlust-india-premium.vercel.app/",
        "media": [
            {
                "type": "image",
                "url": "https://screenshot.microlink.io/https%3A%2F%2Fwanderlust-india-premium.vercel.app%2F"
            }
        ]
    }
];
